# CITY

cities:
    path: /cities
    controller: App\Controller\FrontController::cities

cityRandom:
    path: /city/random
    controller: App\Controller\FrontController::cityRandom

# STATE

states:
    path: /states
    controller: App\Controller\FrontController::states

# OTHERS

search:
    path: /search/{query}
    controller: App\Controller\FrontController::search